/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface history {
  messages: ({
    content: string;
    role: 'user' | 'system' | 'assistant';
  })[];
}

export interface message {
  content: string;
  role: 'user' | 'system' | 'assistant';
}

export interface systemMessage {
  content: string;
  key: string;
  role?: string;
}
