/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createSystemMessage {
  body: {
    id: string;
  };
  query: {
    key: string;
  };
}

export interface deleteSystemMessage {
  query: {
    key: string;
  };
}

export interface getSystemMessage {
  query: {
    key: string;
  };
}

export interface getSystemMessages {
  query: {
    key?: string;
  };
}

export interface updateSystemMessage {
  body: {
    id: string;
  };
  query: {
    key: string;
  };
}
