/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createSystemMessage {
  body?: {
    content: string;
    key: string;
    role?: string;
  };
  query?: object;
}

export interface deleteSystemMessage {
  query?: {
    key: string;
  };
}

export interface getSystemMessage {
  query?: {
    key: string;
  };
}

export interface getSystemMessages {
  query?: {
    key?: string;
  };
}

export interface updateSystemMessage {
  body?: {
    content: string;
    key: string;
    role?: string;
  };
  query?: {
    key: string;
  };
}
