/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface interactiveChatResponse {
  'response-type'?: 'function-call' | 'assistant';
  call?: string;
  content?: string;
}
